server:
  port: 8080
spring:
  application:
    name: "ExampleCleanArchitecture"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:h2:mem:test"
    #url: "jdbc:postgresql://database-1.c8ybgajf3alv.us-east-2.rds.amazonaws.com:5432/basedatosusuarios"
    username: prueba
    password:
    #username: "postgres"
    #password: "1q2w3e4r5t6y"
    driverClassName: "org.h2.Driver"
    #driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
    #databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
    #database: POSTGRESQL

